# Generated by Django 3.0.6 on 2021-01-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100, null=True)),
                ('publication_date', models.DateField(null=True)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=100)),
                ('school_principal', models.CharField(max_length=100)),
                ('school_number', models.CharField(default=0, max_length=12)),
                ('school_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_details.Book')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_details.School')),
            ],
        ),
    ]
