# Generated by Django 3.0.6 on 2021-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_details', '0002_auto_20210124_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
